export type PackageCategory = "Beach" | "City" | "Adventure" | "Family" | "Romantic";

export type PromoPackage = {
  id: string;
  title: string;
  destination: string;
  destinationCode: string;
  country: string;
  nights: number;
  hotel: string;
  hotelStars: number;
  includesCar: boolean;
  category: PackageCategory;
  price: number;
  originalPrice: number;
  rating: number;
  reviews: number;
  perks: string[];
  gradient: string;
  badge?: string;
};

export const PACKAGE_CATEGORIES: PackageCategory[] = [
  "Beach",
  "City",
  "Adventure",
  "Family",
  "Romantic",
];

export const PROMO_PACKAGES: PromoPackage[] = [
  {
    id: "cancun-all-inclusive",
    title: "Cancún All-Inclusive Escape",
    destination: "Cancún",
    destinationCode: "CUN",
    country: "Mexico",
    nights: 5,
    hotel: "Riviera Coral Beach Resort",
    hotelStars: 5,
    includesCar: false,
    category: "Beach",
    price: 899,
    originalPrice: 1349,
    rating: 4.7,
    reviews: 2381,
    perks: ["Round-trip flights", "All meals & drinks", "Airport transfer"],
    gradient: "from-cyan-400 via-sky-500 to-blue-700",
    badge: "Best seller",
  },
  {
    id: "bali-villa-car",
    title: "Bali Villa + Scooter & Car",
    destination: "Bali",
    destinationCode: "DPS",
    country: "Indonesia",
    nights: 7,
    hotel: "Ubud Jungle Pool Villas",
    hotelStars: 4,
    includesCar: true,
    category: "Romantic",
    price: 1129,
    originalPrice: 1690,
    rating: 4.8,
    reviews: 1544,
    perks: ["Round-trip flights", "Private pool villa", "7-day car rental"],
    gradient: "from-emerald-400 via-teal-500 to-cyan-700",
    badge: "Save 33%",
  },
  {
    id: "paris-city-break",
    title: "Paris City Break",
    destination: "Paris",
    destinationCode: "CDG",
    country: "France",
    nights: 4,
    hotel: "Hôtel Le Marais Boutique",
    hotelStars: 4,
    includesCar: false,
    category: "City",
    price: 749,
    originalPrice: 1020,
    rating: 4.6,
    reviews: 3102,
    perks: ["Round-trip flights", "Daily breakfast", "Seine river cruise"],
    gradient: "from-rose-400 via-pink-500 to-purple-700",
  },
  {
    id: "orlando-family-fun",
    title: "Orlando Family Fun + Car",
    destination: "Orlando",
    destinationCode: "MCO",
    country: "United States",
    nights: 6,
    hotel: "Lakeside Family Suites",
    hotelStars: 4,
    includesCar: true,
    category: "Family",
    price: 1049,
    originalPrice: 1480,
    rating: 4.5,
    reviews: 4210,
    perks: ["Round-trip flights", "Kids stay free", "SUV rental included"],
    gradient: "from-amber-300 via-orange-400 to-rose-600",
    badge: "Family pick",
  },
  {
    id: "dubai-luxury",
    title: "Dubai Luxury Stopover",
    destination: "Dubai",
    destinationCode: "DXB",
    country: "United Arab Emirates",
    nights: 4,
    hotel: "Marina Skyline Hotel",
    hotelStars: 5,
    includesCar: false,
    category: "City",
    price: 1199,
    originalPrice: 1650,
    rating: 4.7,
    reviews: 1876,
    perks: ["Round-trip flights", "Desert safari", "Breakfast included"],
    gradient: "from-yellow-300 via-amber-500 to-orange-700",
  },
  {
    id: "tokyo-explorer",
    title: "Tokyo Explorer",
    destination: "Tokyo",
    destinationCode: "NRT",
    country: "Japan",
    nights: 6,
    hotel: "Shinjuku Garden Hotel",
    hotelStars: 4,
    includesCar: false,
    category: "City",
    price: 1399,
    originalPrice: 1890,
    rating: 4.8,
    reviews: 2655,
    perks: ["Round-trip flights", "7-day rail pass", "Airport limousine bus"],
    gradient: "from-fuchsia-400 via-rose-500 to-red-600",
  },
  {
    id: "hawaii-road-trip",
    title: "Hawaiʻi Beach & Road Trip",
    destination: "Honolulu",
    destinationCode: "HNL",
    country: "United States",
    nights: 7,
    hotel: "Waikiki Shore Resort",
    hotelStars: 4,
    includesCar: true,
    category: "Adventure",
    price: 1549,
    originalPrice: 2190,
    rating: 4.6,
    reviews: 1320,
    perks: ["Round-trip flights", "Convertible rental", "Snorkel tour"],
    gradient: "from-sky-300 via-cyan-500 to-teal-700",
    badge: "Limited time",
  },
  {
    id: "cebu-island-hopping",
    title: "Cebu Island Hopping",
    destination: "Cebu",
    destinationCode: "CEB",
    country: "Philippines",
    nights: 5,
    hotel: "Mactan Blue Lagoon Resort",
    hotelStars: 4,
    includesCar: false,
    category: "Beach",
    price: 689,
    originalPrice: 980,
    rating: 4.7,
    reviews: 987,
    perks: ["Round-trip flights", "Island hopping tour", "Breakfast included"],
    gradient: "from-teal-300 via-emerald-500 to-green-700",
  },
  {
    id: "rome-romance",
    title: "Roman Holiday for Two",
    destination: "Rome",
    destinationCode: "FCO",
    country: "Italy",
    nights: 5,
    hotel: "Trastevere Charm Hotel",
    hotelStars: 4,
    includesCar: true,
    category: "Romantic",
    price: 959,
    originalPrice: 1310,
    rating: 4.6,
    reviews: 1702,
    perks: ["Round-trip flights", "Tuscany day-trip car", "Wine tasting"],
    gradient: "from-orange-300 via-red-400 to-rose-700",
  },
];

export const HOW_BUNDLES_SAVE = [
  { item: "Flight", price: 620 },
  { item: "Hotel (5 nights)", price: 540 },
  { item: "Car rental", price: 190 },
];
